# Generated by Django 2.0.7 on 2018-07-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=50)),
                ('l_pass', models.CharField(max_length=50)),
                ('u_name', models.CharField(max_length=50)),
                ('u_sex', models.BooleanField()),
                ('u_phone', models.CharField(max_length=50)),
            ],
        ),
    ]
