# Generated by Django 2.0.7 on 2018-07-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManage', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=500)),
                ('p_desc', models.TextField()),
                ('p_create_datetime', models.DateTimeField()),
                ('p_fail_datetime', models.DateTimeField()),
                ('p_has_append', models.BooleanField()),
                ('p_has_desc_files', models.BooleanField()),
                ('p_status', models.IntegerField()),
                ('p_create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManage.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
