# Generated by Django 2.0.7 on 2018-07-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManage', '0003_auto_20180724_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_name', models.CharField(max_length=50)),
            ],
        ),
    ]
