# Generated by Django 2.0.7 on 2018-07-26 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManage', '0005_user_u_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100)),
                ('superior_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManage.Department')),
            ],
        ),
    ]
