# Generated by Django 2.0.7 on 2018-07-26 01:52

import ProjectManage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManage', '0006_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_department',
            field=models.ForeignKey(null=True, on_delete=models.SET(ProjectManage.models.func), to='ProjectManage.Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='superior_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManage.Department'),
        ),
    ]
