# Generated by Django 2.0.7 on 2018-07-26 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManage', '0009_auto_20180726_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='superior_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManage.Department'),
        ),
    ]
