# Generated by Django 2.0.7 on 2018-07-26 02:44

import ProjectManage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManage', '0010_auto_20180726_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_paper', models.BooleanField()),
                ('pf_path', models.CharField(max_length=1000)),
                ('ef_path', models.FilePathField()),
                ('f_manager', models.ForeignKey(on_delete=models.SET(ProjectManage.models.func), to='ProjectManage.User')),
            ],
        ),
        migrations.CreateModel(
            name='File_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('management_department', models.ForeignKey(on_delete=models.SET(ProjectManage.models.func), to='ProjectManage.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Sys_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='company_file',
            name='f_type',
            field=models.ForeignKey(on_delete=models.SET(ProjectManage.models.func), to='ProjectManage.File_type'),
        ),
    ]
