# Generated by Django 2.0.7 on 2018-07-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManage', '0011_auto_20180726_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_file',
            name='f_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
