# Generated by Django 2.0.7 on 2018-07-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManage', '0013_auto_20180726_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_name', models.CharField(max_length=50)),
            ],
        ),
    ]
